x = input("Digite qualquer coisa: ")
print(f"O tipo primitivo de {x} é {type(x)}")
print(f"Só tem espaços? - {x.isspace()}")
print(f"É um número? - {x.isnumeric()}")
print(f"É alfabético? - {x.isalpha()}")
print(f"É alfanumérico? - {x.isalnum()}")
print(f"Está em maiúsculas? - {x.isupper()}")
print(f"Está em minúsculas? - {x.islower()}")
print(f"Está Capitalizada? - {x.istitle()}")